/*
 * This file is generated by jOOQ.
 */
package db.tables.daos;


import db.tables.Waybillcontent;
import db.tables.records.WaybillcontentRecord;

import java.util.List;

import javax.annotation.processing.Generated;

import org.jooq.Configuration;
import org.jooq.impl.DAOImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "https://www.jooq.org",
        "jOOQ version:3.14.0"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class WaybillcontentDao extends DAOImpl<WaybillcontentRecord, db.tables.pojos.Waybillcontent, Integer> {

    /**
     * Create a new WaybillcontentDao without any configuration
     */
    public WaybillcontentDao() {
        super(Waybillcontent.WAYBILLCONTENT, db.tables.pojos.Waybillcontent.class);
    }

    /**
     * Create a new WaybillcontentDao with an attached configuration
     */
    public WaybillcontentDao(Configuration configuration) {
        super(Waybillcontent.WAYBILLCONTENT, db.tables.pojos.Waybillcontent.class, configuration);
    }

    @Override
    public Integer getId(db.tables.pojos.Waybillcontent object) {
        return object.getId();
    }

    /**
     * Fetch records that have <code>id BETWEEN lowerInclusive AND upperInclusive</code>
     */
    public List<db.tables.pojos.Waybillcontent> fetchRangeOfId(Integer lowerInclusive, Integer upperInclusive) {
        return fetchRange(Waybillcontent.WAYBILLCONTENT.ID, lowerInclusive, upperInclusive);
    }

    /**
     * Fetch records that have <code>id IN (values)</code>
     */
    public List<db.tables.pojos.Waybillcontent> fetchById(Integer... values) {
        return fetch(Waybillcontent.WAYBILLCONTENT.ID, values);
    }

    /**
     * Fetch a unique record that has <code>id = value</code>
     */
    public db.tables.pojos.Waybillcontent fetchOneById(Integer value) {
        return fetchOne(Waybillcontent.WAYBILLCONTENT.ID, value);
    }

    /**
     * Fetch records that have <code>price BETWEEN lowerInclusive AND upperInclusive</code>
     */
    public List<db.tables.pojos.Waybillcontent> fetchRangeOfPrice(Integer lowerInclusive, Integer upperInclusive) {
        return fetchRange(Waybillcontent.WAYBILLCONTENT.PRICE, lowerInclusive, upperInclusive);
    }

    /**
     * Fetch records that have <code>price IN (values)</code>
     */
    public List<db.tables.pojos.Waybillcontent> fetchByPrice(Integer... values) {
        return fetch(Waybillcontent.WAYBILLCONTENT.PRICE, values);
    }

    /**
     * Fetch records that have <code>quantity BETWEEN lowerInclusive AND upperInclusive</code>
     */
    public List<db.tables.pojos.Waybillcontent> fetchRangeOfQuantity(Integer lowerInclusive, Integer upperInclusive) {
        return fetchRange(Waybillcontent.WAYBILLCONTENT.QUANTITY, lowerInclusive, upperInclusive);
    }

    /**
     * Fetch records that have <code>quantity IN (values)</code>
     */
    public List<db.tables.pojos.Waybillcontent> fetchByQuantity(Integer... values) {
        return fetch(Waybillcontent.WAYBILLCONTENT.QUANTITY, values);
    }

    /**
     * Fetch records that have <code>nomenclature BETWEEN lowerInclusive AND upperInclusive</code>
     */
    public List<db.tables.pojos.Waybillcontent> fetchRangeOfNomenclature(String lowerInclusive, String upperInclusive) {
        return fetchRange(Waybillcontent.WAYBILLCONTENT.NOMENCLATURE, lowerInclusive, upperInclusive);
    }

    /**
     * Fetch records that have <code>nomenclature IN (values)</code>
     */
    public List<db.tables.pojos.Waybillcontent> fetchByNomenclature(String... values) {
        return fetch(Waybillcontent.WAYBILLCONTENT.NOMENCLATURE, values);
    }
}
