/*
 * This file is generated by jOOQ.
 */
package db.tables.records;


import db.tables.Waybillcontent;

import javax.annotation.processing.Generated;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record4;
import org.jooq.Row4;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "https://www.jooq.org",
        "jOOQ version:3.14.0"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class WaybillcontentRecord extends UpdatableRecordImpl<WaybillcontentRecord> implements Record4<Integer, Integer, Integer, String> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>public.WaybillContent.id</code>.
     */
    public WaybillcontentRecord setId(Integer value) {
        set(0, value);
        return this;
    }

    /**
     * Getter for <code>public.WaybillContent.id</code>.
     */
    public Integer getId() {
        return (Integer) get(0);
    }

    /**
     * Setter for <code>public.WaybillContent.price</code>.
     */
    public WaybillcontentRecord setPrice(Integer value) {
        set(1, value);
        return this;
    }

    /**
     * Getter for <code>public.WaybillContent.price</code>.
     */
    public Integer getPrice() {
        return (Integer) get(1);
    }

    /**
     * Setter for <code>public.WaybillContent.quantity</code>.
     */
    public WaybillcontentRecord setQuantity(Integer value) {
        set(2, value);
        return this;
    }

    /**
     * Getter for <code>public.WaybillContent.quantity</code>.
     */
    public Integer getQuantity() {
        return (Integer) get(2);
    }

    /**
     * Setter for <code>public.WaybillContent.nomenclature</code>.
     */
    public WaybillcontentRecord setNomenclature(String value) {
        set(3, value);
        return this;
    }

    /**
     * Getter for <code>public.WaybillContent.nomenclature</code>.
     */
    public String getNomenclature() {
        return (String) get(3);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<Integer> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record4 type implementation
    // -------------------------------------------------------------------------

    @Override
    public Row4<Integer, Integer, Integer, String> fieldsRow() {
        return (Row4) super.fieldsRow();
    }

    @Override
    public Row4<Integer, Integer, Integer, String> valuesRow() {
        return (Row4) super.valuesRow();
    }

    @Override
    public Field<Integer> field1() {
        return Waybillcontent.WAYBILLCONTENT.ID;
    }

    @Override
    public Field<Integer> field2() {
        return Waybillcontent.WAYBILLCONTENT.PRICE;
    }

    @Override
    public Field<Integer> field3() {
        return Waybillcontent.WAYBILLCONTENT.QUANTITY;
    }

    @Override
    public Field<String> field4() {
        return Waybillcontent.WAYBILLCONTENT.NOMENCLATURE;
    }

    @Override
    public Integer component1() {
        return getId();
    }

    @Override
    public Integer component2() {
        return getPrice();
    }

    @Override
    public Integer component3() {
        return getQuantity();
    }

    @Override
    public String component4() {
        return getNomenclature();
    }

    @Override
    public Integer value1() {
        return getId();
    }

    @Override
    public Integer value2() {
        return getPrice();
    }

    @Override
    public Integer value3() {
        return getQuantity();
    }

    @Override
    public String value4() {
        return getNomenclature();
    }

    @Override
    public WaybillcontentRecord value1(Integer value) {
        setId(value);
        return this;
    }

    @Override
    public WaybillcontentRecord value2(Integer value) {
        setPrice(value);
        return this;
    }

    @Override
    public WaybillcontentRecord value3(Integer value) {
        setQuantity(value);
        return this;
    }

    @Override
    public WaybillcontentRecord value4(String value) {
        setNomenclature(value);
        return this;
    }

    @Override
    public WaybillcontentRecord values(Integer value1, Integer value2, Integer value3, String value4) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached WaybillcontentRecord
     */
    public WaybillcontentRecord() {
        super(Waybillcontent.WAYBILLCONTENT);
    }

    /**
     * Create a detached, initialised WaybillcontentRecord
     */
    public WaybillcontentRecord(Integer id, Integer price, Integer quantity, String nomenclature) {
        super(Waybillcontent.WAYBILLCONTENT);

        setId(id);
        setPrice(price);
        setQuantity(quantity);
        setNomenclature(nomenclature);
    }
}
