/*
 * This file is generated by jOOQ.
 */
package db.tables.records;


import db.tables.Waybill;

import javax.annotation.processing.Generated;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record4;
import org.jooq.Row4;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "https://www.jooq.org",
        "jOOQ version:3.14.0"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class WaybillRecord extends UpdatableRecordImpl<WaybillRecord> implements Record4<Integer, Integer, String, String> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>public.Waybill.id</code>.
     */
    public WaybillRecord setId(Integer value) {
        set(0, value);
        return this;
    }

    /**
     * Getter for <code>public.Waybill.id</code>.
     */
    public Integer getId() {
        return (Integer) get(0);
    }

    /**
     * Setter for <code>public.Waybill.number</code>.
     */
    public WaybillRecord setNumber(Integer value) {
        set(1, value);
        return this;
    }

    /**
     * Getter for <code>public.Waybill.number</code>.
     */
    public Integer getNumber() {
        return (Integer) get(1);
    }

    /**
     * Setter for <code>public.Waybill.date</code>.
     */
    public WaybillRecord setDate(String value) {
        set(2, value);
        return this;
    }

    /**
     * Getter for <code>public.Waybill.date</code>.
     */
    public String getDate() {
        return (String) get(2);
    }

    /**
     * Setter for <code>public.Waybill.organisation</code>.
     */
    public WaybillRecord setOrganisation(String value) {
        set(3, value);
        return this;
    }

    /**
     * Getter for <code>public.Waybill.organisation</code>.
     */
    public String getOrganisation() {
        return (String) get(3);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<Integer> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record4 type implementation
    // -------------------------------------------------------------------------

    @Override
    public Row4<Integer, Integer, String, String> fieldsRow() {
        return (Row4) super.fieldsRow();
    }

    @Override
    public Row4<Integer, Integer, String, String> valuesRow() {
        return (Row4) super.valuesRow();
    }

    @Override
    public Field<Integer> field1() {
        return Waybill.WAYBILL.ID;
    }

    @Override
    public Field<Integer> field2() {
        return Waybill.WAYBILL.NUMBER;
    }

    @Override
    public Field<String> field3() {
        return Waybill.WAYBILL.DATE;
    }

    @Override
    public Field<String> field4() {
        return Waybill.WAYBILL.ORGANISATION;
    }

    @Override
    public Integer component1() {
        return getId();
    }

    @Override
    public Integer component2() {
        return getNumber();
    }

    @Override
    public String component3() {
        return getDate();
    }

    @Override
    public String component4() {
        return getOrganisation();
    }

    @Override
    public Integer value1() {
        return getId();
    }

    @Override
    public Integer value2() {
        return getNumber();
    }

    @Override
    public String value3() {
        return getDate();
    }

    @Override
    public String value4() {
        return getOrganisation();
    }

    @Override
    public WaybillRecord value1(Integer value) {
        setId(value);
        return this;
    }

    @Override
    public WaybillRecord value2(Integer value) {
        setNumber(value);
        return this;
    }

    @Override
    public WaybillRecord value3(String value) {
        setDate(value);
        return this;
    }

    @Override
    public WaybillRecord value4(String value) {
        setOrganisation(value);
        return this;
    }

    @Override
    public WaybillRecord values(Integer value1, Integer value2, String value3, String value4) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached WaybillRecord
     */
    public WaybillRecord() {
        super(Waybill.WAYBILL);
    }

    /**
     * Create a detached, initialised WaybillRecord
     */
    public WaybillRecord(Integer id, Integer number, String date, String organisation) {
        super(Waybill.WAYBILL);

        setId(id);
        setNumber(number);
        setDate(date);
        setOrganisation(organisation);
    }
}
