/*
 * This file is generated by jOOQ.
 */
package db;


import db.tables.Nomenclature;
import db.tables.Organisation;
import db.tables.Waybill;
import db.tables.Waybillcontent;
import db.tables.records.NomenclatureRecord;
import db.tables.records.OrganisationRecord;
import db.tables.records.WaybillRecord;
import db.tables.records.WaybillcontentRecord;

import javax.annotation.processing.Generated;

import org.jooq.TableField;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.Internal;


/**
 * A class modelling foreign key relationships and constraints of tables in 
 * public.
 */
@Generated(
    value = {
        "https://www.jooq.org",
        "jOOQ version:3.14.0"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Keys {

    // -------------------------------------------------------------------------
    // UNIQUE and PRIMARY KEY definitions
    // -------------------------------------------------------------------------

    public static final UniqueKey<NomenclatureRecord> NOMENCLATURE_PKEY = Internal.createUniqueKey(Nomenclature.NOMENCLATURE, DSL.name("Nomenclature_pkey"), new TableField[] { Nomenclature.NOMENCLATURE.ID }, true);
    public static final UniqueKey<OrganisationRecord> ORGANISATION_PKEY = Internal.createUniqueKey(Organisation.ORGANISATION, DSL.name("Organisation_pkey"), new TableField[] { Organisation.ORGANISATION.ID }, true);
    public static final UniqueKey<WaybillRecord> WAYBILL_PKEY = Internal.createUniqueKey(Waybill.WAYBILL, DSL.name("Waybill_pkey"), new TableField[] { Waybill.WAYBILL.ID }, true);
    public static final UniqueKey<WaybillcontentRecord> WAYBILLCONTENT_PKEY = Internal.createUniqueKey(Waybillcontent.WAYBILLCONTENT, DSL.name("WaybillContent_pkey"), new TableField[] { Waybillcontent.WAYBILLCONTENT.ID }, true);
}
