/*
 * This file is generated by jOOQ.
 */
package db;


import db.tables.Nomenclature;
import db.tables.Organisation;
import db.tables.Waybill;
import db.tables.Waybillcontent;

import java.util.Arrays;
import java.util.List;

import javax.annotation.processing.Generated;

import org.jooq.Catalog;
import org.jooq.Table;
import org.jooq.impl.SchemaImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "https://www.jooq.org",
        "jOOQ version:3.14.0"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Public extends SchemaImpl {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>public</code>
     */
    public static final Public PUBLIC = new Public();

    /**
     * The table <code>public.Nomenclature</code>.
     */
    public final Nomenclature NOMENCLATURE = Nomenclature.NOMENCLATURE;

    /**
     * The table <code>public.Organisation</code>.
     */
    public final Organisation ORGANISATION = Organisation.ORGANISATION;

    /**
     * The table <code>public.Waybill</code>.
     */
    public final Waybill WAYBILL = Waybill.WAYBILL;

    /**
     * The table <code>public.WaybillContent</code>.
     */
    public final Waybillcontent WAYBILLCONTENT = Waybillcontent.WAYBILLCONTENT;

    /**
     * No further instances allowed
     */
    private Public() {
        super("public", null);
    }


    @Override
    public Catalog getCatalog() {
        return DefaultCatalog.DEFAULT_CATALOG;
    }

    @Override
    public final List<Table<?>> getTables() {
        return Arrays.<Table<?>>asList(
            Nomenclature.NOMENCLATURE,
            Organisation.ORGANISATION,
            Waybill.WAYBILL,
            Waybillcontent.WAYBILLCONTENT);
    }
}
